language: php

before_script:
  - composer install
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - php vendor/bin/phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v
